### ISSUE TITLE
Figure out what the hell this game is going to be about

### ISSUE THREAD

**Issue by tvanantwerp** [marginal-utilities/game-off-2016#1]
The theme is hacking/modding/augmenting. It's a loose them with lots of room for interpretation.

The first goal of this (or any) game should be to make something that's fun to play.

Let's list game ideas as comments to this issue. When we're both happy with pursuing any one of these ideas over the rest, issue closed and gamedev begun!

Also, @jdkolassa go watch this on Netflix: http://www.imdb.com/title/tt1942884/

**Comment by tvanantwerp** [comment]
Idea #1

A [Reigns](http://www.devolverdigital.com/games/view/reigns)-style game where you try to win a political election as a third party candidate. Only win condition is to hack the electronic voting machines.

**Comment by tvanantwerp** [comment]
Idea #2

VR game where your start with human arms and slowly body-mod your way to awesome robot arms with guns and lasers and stuff.

**Comment by jdkolassa** [comment]
A game where you hack underlying code of reality by altering the laws of physics, select and introduce various forms of magic/psionics/The Force, bring in monsters and creatures and species, seeing how far you can go before you screw up and the universe collapses. You win by making more changes than all the other players. Lots of snide commentary.

**Comment by jdkolassa** [comment]
A fashion game where you can only dress up characters in mod outfits from the 70s.

**Comment by jdkolassa** [comment]
Garbage Disposal: A fantasy hack and slash game where you have to go into a medieval dump and kill all sorts of varmints, many of which can breathe fire. (Reminds me of the early "dungeons" in Avernum.)

**Comment by tvanantwerp** [comment]
A game where you are an IT Wizard, running around the office fixing problems with magical IT wizard powers and not, like, hard work and expert knowledge or anything.

**Comment by jdkolassa** [comment]
^ But you have to do it by solving math problems

**Comment by tvanantwerp** [comment]
Maybe we should try this: http://orteil.dashnet.org/gamegen

**Comment by tvanantwerp** [comment]
Just remembered my last Ludum Dare was sort of a game about keeping a hacked together Metro running.

http://www.tomvanantwerp.com/ld36/

**Comment by jdkolassa** [comment]
"An adventure game where you save the world with bunnies to forge the sacred sword."

As someone who grew up as a bunny rancher, I fully support this and will create this game some day.

**Comment by jdkolassa** [comment]
"A sim game where you build limbs to make money."

You know what, this was similar enough to our VR game, let's go with this. Instead of actually making your own arms to fight people, you just hack together arms (and legs) and sell them to people for outrageous money...but if you charge too much you piss off the cost police and then you have to fight them off with either bribes, lobbyists, or lead.

**Comment by tvanantwerp** [comment]
What kind of genre would that be? Resource management meets FPS?

**Comment by jdkolassa** [comment]
....yes?

**Comment by tvanantwerp** [comment]
Let's hash it out this weekend.

Also, ironically, I think I'm already playing this game...

> An artsy game where you hide from politics and also you push around blocks.

**Comment by jdkolassa** [comment]
I also got and want to make:

> An FPS where you cheer up sad mutants but bees have other ideas.

**Comment by tvanantwerp** [comment]
Tronfox. It's Tronfox.
